export const cardSetsData = {
  'en': [
    { id: 10031, name: 'Resurgent Legends' },
    { id: 10030, name: 'Order Shift' },
    { id: 10029, name: 'Heroes of Rivenbrandt' },
    { id: 10028, name: 'Academy of Ages' },
    { id: 10027, name: 'Eightfold Abyss: Azvaldt' },
    { id: 10026, name: 'Celestial Dragonblade' },
    { id: 10025, name: 'Roar of the Godwyrm' },
    { id: 10024, name: 'Edge of Paradise' },
    { id: 10023, name: 'Omen of Storms' },
    { id: 10022, name: 'Dawn of Calamity' },
    { id: 10021, name: 'Renascent Chronicles' },
    { id: 10020, name: 'Darkness Over Vellsar' },
    { id: 10019, name: 'Eternal Awakening' },
    { id: 10018, name: 'Storm Over Rivayle' },
    { id: 10017, name: 'Fortune\'s Hand' },
    { id: 10016, name: 'World Uprooted' },
    { id: 10015, name: 'Ultimate Colosseum' },
    { id: 10014, name: 'Verdant Conflict' },
    { id: 10013, name: 'Rebirth of Glory' },
    { id: 10012, name: 'Steel Rebellion' },
    { id: 10011, name: 'Altersphere' },
    { id: 10010, name: 'Omen of the Ten' },
    { id: 10009, name: 'Brigade of the Sky' },
    { id: 10008, name: 'Dawnbreak, Nightedge' },
    { id: 10007, name: 'Chronogenesis' },
    { id: 10006, name: 'Starforged Legends' },
    { id: 10005, name: 'Wonderland Dreams' },
    { id: 10004, name: 'Tempest of the Gods' },
    { id: 10003, name: 'Rise of Bahamut' },
    { id: 10002, name: 'Darkness Evolved' },
    { id: 10001, name: 'Classic' },
    { id: 10000, name: 'Basic' },
    { id: 70001, name: 'Prebuilt Decks Set 1' },
    { id: 70002, name: 'Prebuilt Decks Set 2' },
    { id: 70003, name: 'Anigera Didoooon Tie-In' },
    { id: 70004, name: 'Fate/stay night [Heaven\'s Feel] Tie-In' },
    { id: 70005, name: 'Prebuilt Decks Set 4' },
    { id: 70006, name: 'Prebuilt Decks Set 5' },
    { id: 70008, name: 'Princess Connect! Re:Dive Tie-In' },
    { id: 70009, name: 'One-Punch Man Tie-In' },
    { id: 70010, name: 'Re:ZERO Tie-In' },
    { id: 70011, name: 'Prebuilt Decks Set 6' },
    { id: 70012, name: 'Love Live! School Idol Festival Tie-In' },
    { id: 70013, name: 'The Melancholy of Haruhi Suzumiya Tie-In' },
    { id: 70014, name: 'Prebuilt Decks Set 7' },
    { id: 70016, name: 'NieR:Automata Tie-In' },
    { id: 70017, name: 'Code Geass Lelouch of the Rebellion Tie-In' },
    { id: 70018, name: 'Shadowverse: Champion\'s Battle Tie-In' },
    { id: 70019, name: 'Shadowverse: Champion\'s Battle Set' },
    { id: 70020, name: 'Granblue Fantasy Tie-In' },
    { id: 70021, name: 'Battle Pass' },
    { id: 70022, name: 'Kaguya-sama: Love Is War? Tie-In' },
    { id: 70023, name: 'The Idolmaster: Cinderella Girls Tie-In' },
    { id: 70024, name: 'Shaman King Tie-In' },
    { id: 70025, name: 'Umamusume: Pretty Derby Tie-In' },
    { id: 70026, name: 'Chiikawa Tie-In' },
    { id: 70027, name: 'Shadowverse Flame Tie-In' },
    { id: 70028, name: 'Hatsune Miku Tie-In' },
    { id: 70029, name: 'Sanrio Characters Tie-In' },
    { id: 70030, name: 'SPY x FAMILY Tie-In' },
  ],

  'zh-tw': [
    { id: 10031, name: '傳說復甦' },
    { id: 10030, name: '變革的恆規' },
    { id: 10029, name: '密斯塔爾西亞的英雄' },
    { id: 10028, name: '遙久學園' },
    { id: 10027, name: '八獄魔境‧阿茲弗特' },
    { id: 10026, name: '示天龍劍' },
    { id: 10025, name: '極天龍鳴' },
    { id: 10024, name: '天象樂土' },
    { id: 10023, name: '十禍鬥爭' },
    { id: 10022, name: '超越災禍者' },
    { id: 10021, name: '物語重歸' },
    { id: 10020, name: '暗黑的威爾薩' },
    { id: 10019, name: '十天覺醒' },
    { id: 10018, name: '勒比盧的旋風' },
    { id: 10017, name: '命運諸神' },
    { id: 10016, name: '那塔拉的崩壞' },
    { id: 10015, name: '極鬥之巔' },
    { id: 10014, name: '森羅咆哮' },
    { id: 10013, name: '榮耀再臨' },
    { id: 10012, name: '鋼鐵的反叛者' },
    { id: 10011, name: '扭曲次元' },
    { id: 10010, name: '滅禍十傑' },
    { id: 10009, name: '蒼空騎翔' },
    { id: 10008, name: '起源之光‧終焉之闇' },
    { id: 10007, name: '時空轉生' },
    { id: 10006, name: '星神傳說' },
    { id: 10005, name: '夢境奇想' },
    { id: 10004, name: '諸神狂嵐' },
    { id: 10003, name: '巴哈姆特降臨' },
    { id: 10002, name: '暗影進化' },
    { id: 10001, name: '經典卡包' },
    { id: 10000, name: '基本卡' },
    { id: 70001, name: '主題牌組 第1彈' },
    { id: 70002, name: '主題牌組 第2彈' },
    { id: 70003, name: 'Anigera合作' },
    { id: 70004, name: '劇場版Fate[HF]合作' },
    { id: 70005, name: '主題牌組 第4彈' },
    { id: 70006, name: '主題牌組 第5彈' },
    { id: 70008, name: '超異域公主連結！Re:Dive合作' },
    { id: 70009, name: '一拳超人合作' },
    { id: 70010, name: 'Re：從零開始的異世界生活合作' },
    { id: 70011, name: '主題牌組 第6彈' },
    { id: 70012, name: 'Love Live! 學園偶像祭合作' },
    { id: 70013, name: '涼宮春日的憂鬱合作' },
    { id: 70014, name: '主題牌組 第7彈' },
    { id: 70016, name: '尼爾：自動人形合作' },
    { id: 70017, name: 'CODE GEASS 反叛的魯路修合作' },
    { id: 70018, name: '闇影詩章‧霸者之戰合作' },
    { id: 70019, name: '闇影詩章‧霸者之戰套組' },
    { id: 70020, name: '碧藍幻想合作' },
    { id: 70021, name: '對戰通行證' },
    { id: 70022, name: '輝夜姬想讓人告白？合作' },
    { id: 70023, name: '偶像大師 灰姑娘女孩合作' },
    { id: 70024, name: '通靈王合作' },
    { id: 70025, name: '賽馬娘Pretty Derby合作' },
    { id: 70026, name: '吉伊卡哇合作' },
    { id: 70027, name: '闇影詩章F合作' },
    { id: 70028, name: '初音未來合作' },
    { id: 70029, name: '三麗鷗明星合作' },
    { id: 70030, name: 'SPY×FAMILY合作' },
  ],
  'ja': [
    { id: 10031, name: 'リサージェント・レジェンズ' },
    { id: 10030, name: 'オーダーシフト' },
    { id: 10029, name: 'ミスタルシアの英雄' },
    { id: 10028, name: '遥かなる学園' },
    { id: 10027, name: '八獄魔境アズヴォルト' },
    { id: 10026, name: '天示す竜剣' },
    { id: 10025, name: '極天竜鳴' },
    { id: 10024, name: '天象の楽土' },
    { id: 10023, name: '十禍闘争' },
    { id: 10022, name: '災禍を超えし者' },
    { id: 10021, name: 'リナセント・クロニクル' },
    { id: 10020, name: '暗黒のウェルサ' },
    { id: 10019, name: '十天覚醒' },
    { id: 10018, name: 'レヴィールの旋風' },
    { id: 10017, name: '運命の神々' },
    { id: 10016, name: 'ナテラ崩壊' },
    { id: 10015, name: 'アルティメットコロシアム' },
    { id: 10014, name: '森羅咆哮' },
    { id: 10013, name: 'リバース・オブ・グローリー' },
    { id: 10012, name: '鋼鉄の反逆者' },
    { id: 10011, name: '次元歪曲' },
    { id: 10010, name: '十禍絶傑' },
    { id: 10009, name: '蒼空の騎士' },
    { id: 10008, name: '起源の光、終焉の闇' },
    { id: 10007, name: '時空転生' },
    { id: 10006, name: '星神の伝説' },
    { id: 10005, name: 'ワンダーランド・ドリームズ' },
    { id: 10004, name: '神々の騒嵐' },
    { id: 10003, name: 'バハムート降臨' },
    { id: 10002, name: 'ダークネス・エボルヴ' },
    { id: 10001, name: 'クラシックカードパック' },
    { id: 10000, name: 'ベーシックカード' },
    { id: 70001, name: '構築済みデッキ 第1弾' },
    { id: 70002, name: '構築済みデッキ 第2弾' },
    { id: 70003, name: 'アニゲラコラボ' },
    { id: 70004, name: '劇場版Fate[HF]コラボ' },
    { id: 70005, name: '構築済みデッキ 第4弾' },
    { id: 70006, name: '構築済みデッキ 第5弾' },
    { id: 70008, name: 'プリンセスコネクト！Re:Diveコラボ' },
    { id: 70009, name: 'ワンパンマンコラボ' },
    { id: 70010, name: 'Re:ゼロから始める異世界生活コラボ' },
    { id: 70011, name: '構築済みデッキ 第6弾' },
    { id: 70012, name: 'ラブライブ！スクールアイドルフェスティバルコラボ' },
    { id: 70013, name: '涼宮ハルヒの憂鬱コラボ' },
    { id: 70014, name: '構築済みデッキ 第7弾' },
    { id: 70016, name: 'NieR:Automataコラボ' },
    { id: 70017, name: 'コードギアス 反逆のルルーシュコラボ' },
    { id: 70018, name: 'シャドウバース チャンピオンズバトルコラボ' },
    { id: 70019, name: 'シャドウバース チャンピオンズバトルセット' },
    { id: 70020, name: 'グランブルーファンタジーコラボ' },
    { id: 70021, name: 'バトルパス' },
    { id: 70022, name: 'かぐや様は告らせたい？コラボ' },
    { id: 70023, name: 'アイドルマスター シンデレラガールズコラボ' },
    { id: 70024, name: 'SHAMAN KINGコラボ' },
    { id: 70025, name: 'ウマ娘 プリティーダービーコラボ' },
    { id: 70026, name: 'ちいかわコラボ' },
    { id: 70027, name: 'シャドウバースＦコラボ' },
    { id: 70028, name: '初音ミクコラボ' },
    { id: 70029, name: 'サンリオキャラクターズコラボ' },
    { id: 70030, name: 'SPY×FAMILYコラボ' },
  ],
} as const;

export const clansData = {
  'en': [
    { id: 0, name: 'Neutral' },
    { id: 1, name: 'Forestcraft' },
    { id: 2, name: 'Swordcraft' },
    { id: 3, name: 'Runecraft' },
    { id: 4, name: 'Dragoncraft' },
    { id: 5, name: 'Shadowcraft' },
    { id: 6, name: 'Bloodcraft' },
    { id: 7, name: 'Havencraft' },
    { id: 8, name: 'Portalcraft' },
  ],

  'zh-tw': [
    { id: 0, name: '中立' },
    { id: 1, name: '精靈' },
    { id: 2, name: '皇家' },
    { id: 3, name: '巫師' },
    { id: 4, name: '龍族' },
    { id: 5, name: '死靈法師' },
    { id: 6, name: '吸血鬼' },
    { id: 7, name: '主教' },
    { id: 8, name: '復仇者' },
  ],

  'ja': [
    { id: 0, name: 'ニュートラル' },
    { id: 1, name: 'エルフ' },
    { id: 2, name: 'ロイヤル' },
    { id: 3, name: 'ウィッチ' },
    { id: 4, name: 'ドラゴン' },
    { id: 5, name: 'ネクロマンサー' },
    { id: 6, name: 'ヴァンパイア' },
    { id: 7, name: 'ビショップ' },
    { id: 8, name: 'ネメシス' },
  ],
} as const;

export const charTypesData = {
  'en': [
    { id: 1, name: 'Follower' },
    { id: 2, name: 'Amulet' },
    { id: 3, name: 'Amulet (Countdown)' },
    { id: 4, name: 'Spell' },
  ],

  'zh-tw': [
    { id: 1, name: '隨從' },
    { id: 2, name: '護符' },
    { id: 3, name: '護符（倒數）' },
    { id: 4, name: '法術' },
  ],

  'ja': [
    { id: 1, name: 'フォロワー' },
    { id: 2, name: 'アミュレット' },
    { id: 3, name: 'アミュレット（カウントダウン）' },
    { id: 4, name: 'スペル' },
  ],
} as const;

export const tribeNamesData = {
  'en': [
    { id: 0, name: '-' },
    { id: 1, name: 'Academic' },
    { id: 2, name: 'All' },
    { id: 3, name: 'Armed' },
    { id: 4, name: 'Artifact' },
    { id: 5, name: 'Chess' },
    { id: 6, name: 'Cmdr./Acad.' },
    { id: 7, name: 'Cmdr./Cdmn.' },
    { id: 8, name: 'Cmdr./Fes.' },
    { id: 9, name: 'Cmdr./Hero.' },
    { id: 10, name: 'Cmdr./Lvn.' },
    { id: 11, name: 'Cmdr./Mach.' },
    { id: 12, name: 'Cmdr./Nat.' },
    { id: 13, name: 'Commander' },
    { id: 14, name: 'Condemned' },
    { id: 15, name: 'Earth Sigil' },
    { id: 16, name: 'Festive' },
    { id: 17, name: 'Heroic' },
    { id: 18, name: 'Levin' },
    { id: 19, name: 'Loot' },
    { id: 20, name: 'Mach./Acad.' },
    { id: 21, name: 'Mach./Art.' },
    { id: 22, name: 'Mach./Cdmn.' },
    { id: 23, name: 'Mach./Fes.' },
    { id: 24, name: 'Mach./Nat.' },
    { id: 25, name: 'Machina' },
    { id: 26, name: 'Mys./Acad.' },
    { id: 27, name: 'Mysteria' },
    { id: 28, name: 'Natura' },
    { id: 29, name: 'Ofcr./Acad.' },
    { id: 30, name: 'Ofcr./Cdmn.' },
    { id: 31, name: 'Ofcr./Fes.' },
    { id: 32, name: 'Ofcr./Hero.' },
    { id: 33, name: 'Ofcr./Lvn.' },
    { id: 34, name: 'Ofcr./Mach.' },
    { id: 35, name: 'Ofcr./Nat.' },
    { id: 36, name: 'Officer' },
  ],
  'zh-tw': [
    { id: 0, name: '-' },
    { id: 1, name: '學園' },
    { id: 2, name: '全部' },
    { id: 3, name: '武裝' },
    { id: 4, name: '創造物' },
    { id: 5, name: '西洋棋' },
    { id: 6, name: '指揮官‧學園' },
    { id: 7, name: '指揮官‧八獄' },
    { id: 8, name: '指揮官‧宴樂' },
    { id: 9, name: '指揮官‧英雄' },
    { id: 10, name: '指揮官‧雷維翁' },
    { id: 11, name: '指揮官‧機械' },
    { id: 12, name: '指揮官‧自然' },
    { id: 13, name: '指揮官' },
    { id: 14, name: '八獄' },
    { id: 15, name: '土之印' },
    { id: 16, name: '宴樂' },
    { id: 17, name: '英雄' },
    { id: 18, name: '雷維翁' },
    { id: 19, name: '財寶' },
    { id: 20, name: '機械‧學園' },
    { id: 21, name: '機械‧創造物' },
    { id: 22, name: '機械‧八獄' },
    { id: 23, name: '機械‧宴樂' },
    { id: 24, name: '機械‧自然' },
    { id: 25, name: '機械' },
    { id: 26, name: '馬納歷亞‧學園' },
    { id: 27, name: '馬納歷亞' },
    { id: 28, name: '自然' },
    { id: 29, name: '士兵‧學園' },
    { id: 30, name: '士兵‧八獄' },
    { id: 31, name: '士兵‧宴樂' },
    { id: 32, name: '士兵‧英雄' },
    { id: 33, name: '士兵‧雷維翁' },
    { id: 34, name: '士兵‧機械' },
    { id: 35, name: '士兵‧自然' },
    { id: 36, name: '士兵' },
  ],

  'ja': [
    { id: 0, name: '-' },
    { id: 1, name: '学園' },
    { id: 2, name: 'すべて' },
    { id: 3, name: '武装' },
    { id: 4, name: 'アーティファクト' },
    { id: 5, name: 'チェス' },
    { id: 6, name: '指揮官・学園' },
    { id: 7, name: '指揮官・八獄' },
    { id: 8, name: '指揮官・宴楽' },
    { id: 9, name: '指揮官・ヒーロー' },
    { id: 10, name: '指揮官・レヴィオン' },
    { id: 11, name: '指揮官・機械' },
    { id: 12, name: '指揮官・自然' },
    { id: 13, name: '指揮官' },
    { id: 14, name: '八獄' },
    { id: 15, name: '土の印' },
    { id: 16, name: '宴楽' },
    { id: 17, name: 'ヒーロー' },
    { id: 18, name: 'レヴィオン' },
    { id: 19, name: '財宝' },
    { id: 20, name: '機械・学園' },
    { id: 21, name: '機械・アーティファクト' },
    { id: 22, name: '機械・八獄' },
    { id: 23, name: '機械・宴楽' },
    { id: 24, name: '機械・自然' },
    { id: 25, name: '機械' },
    { id: 26, name: 'マナリア・学園' },
    { id: 27, name: 'マナリア' },
    { id: 28, name: '自然' },
    { id: 29, name: '兵士・学園' },
    { id: 30, name: '兵士・八獄' },
    { id: 31, name: '兵士・宴楽' },
    { id: 32, name: '兵士・ヒーロー' },
    { id: 33, name: '兵士・レヴィオン' },
    { id: 34, name: '兵士・機械' },
    { id: 35, name: '兵士・自然' },
    { id: 36, name: '兵士' },
  ],
} as const;

export const costData = [
  { id: 0, name: '0' },
  { id: 1, name: '1' },
  { id: 2, name: '2' },
  { id: 3, name: '3' },
  { id: 4, name: '4' },
  { id: 5, name: '5' },
  { id: 6, name: '6' },
  { id: 7, name: '7' },
  { id: 8, name: '8' },
  { id: 9, name: '9' },
  { id: 10, name: '10+' },
] as const;

export const atkData = [
  { id: 0, name: '0' },
  { id: 1, name: '1' },
  { id: 2, name: '2' },
  { id: 3, name: '3' },
  { id: 4, name: '4' },
  { id: 5, name: '5' },
  { id: 6, name: '6' },
  { id: 7, name: '7' },
  { id: 8, name: '8' },
  { id: 9, name: '9' },
  { id: 10, name: '10+' },
] as const;

export const lifeData = [
  { id: 0, name: '0' },
  { id: 1, name: '1' },
  { id: 2, name: '2' },
  { id: 3, name: '3' },
  { id: 4, name: '4' },
  { id: 5, name: '5' },
  { id: 6, name: '6' },
  { id: 7, name: '7' },
  { id: 8, name: '8' },
  { id: 9, name: '9' },
  { id: 10, name: '10+' },
] as const;

export const rarityData = {
  'en': [
    { id: 1, name: 'Bronze' },
    { id: 2, name: 'Silver' },
    { id: 3, name: 'Gold' },
    { id: 4, name: 'Legendary' },
  ],

  'zh-tw': [
    { id: 1, name: '青銅' },
    { id: 2, name: '白銀' },
    { id: 3, name: '黃金' },
    { id: 4, name: '傳說' },
  ],

  'ja': [
    { id: 1, name: 'ブロンズ' },
    { id: 2, name: 'シルバー' },
    { id: 3, name: 'ゴールド' },
    { id: 4, name: 'レジェンド' },
  ],
} as const;

export const formatData = {
  'en': [
    { id: 0, name: 'Unlimited' },
    { id: 1, name: 'Rotation' },
  ],

  'zh-tw': [
    { id: 0, name: '無限制' },
    { id: 1, name: '指定' },
  ],

  'ja': [
    { id: 0, name: 'アンリミテッド' },
    { id: 1, name: 'ローテーション' },
  ],
};

export const restrictedCountData = [
  { id: 0, name: '0' },
  { id: 1, name: '1' },
  { id: 2, name: '2' },
  { id: 3, name: '3' },
] as const;

export const resurgentData = {
  'en': [
    { id: 0, name: 'No' },
    { id: 1, name: 'Yes' },
  ],

  'zh-tw': [
    { id: 0, name: '否' },
    { id: 1, name: '是' },
  ],

  'ja': [
    { id: 0, name: 'いいえ' },
    { id: 1, name: 'はい' },
  ],
} as const;
